name: gala
dependencies:
- python=3.5*
- numpy=1.10*
- h5py=2.5*
- cython=0.23*
- matplotlib=1.5*
- pandas=0.17*
- scipy=0.17*
- scikit-learn=0.17*
- scikit-image=0.11*
- networkx=1.10*
- pyzmq=15.*
- pip:
  - viridis>=0.4
